import React,{useEffect,useState,useRef} from 'react';import {createRoot} from 'react-dom/client';
import {useConvexAuth,useQuery} from 'convex/react';import {ExtensionAuthProvider,useAuthActions,useAuthToken} from '../../src/auth/SharedAuth';import {ConvexHttpClient} from 'convex/browser';import type {FunctionReturnType} from 'convex/server';import {accessIdentity} from './accessIdentity';
import {api} from '../../convex/_generated/api';import {SourceManager} from '../../src/SourceManager';import {AnswerCard} from '../../src/AnswerCheck';
import {sidebarScreen,startBlock} from './sidebarState';import {googlePopup} from './chrome';import {backend} from './client';import {ConvexReactClient} from 'convex/react';import {command} from './runtime';import {initialCallView,type CallView} from './callEngine';
type Source=NonNullable<ReturnType<typeof useQuery<typeof api.sources.get>>>;
function Sidebar(){

 const {isAuthenticated,isLoading}=useConvexAuth(),{signIn,signOut}=useAuthActions();const subscribedAccess=useQuery(api.callAccess.status,isAuthenticated?{}:'skip');const token=useAuthToken();const [checkedAccess,setCheckedAccess]=useState<FunctionReturnType<typeof api.callAccess.status>|null>(null),[checkingAccess,setCheckingAccess]=useState(false),[accessNotice,setAccessNotice]=useState('');const access=checkedAccess??subscribedAccess;const accountId=access?.signedIn?accessIdentity(token,backend):null;
 useEffect(()=>{setCheckedAccess(null);setAccessNotice('');},[subscribedAccess,token]);
 async function checkAccess(){setCheckingAccess(true);setAccessNotice('');try{if(!token)throw Error('Sign in again to check your account.');const connection=new ConvexHttpClient(backend);connection.setAuth(token);const result=await connection.query(api.callAccess.status,{});setCheckedAccess(result);setAccessNotice(result.invited?'Tester access confirmed.':result.signedIn?'The server still reports no tester access for this account. Match the account ID below in the live dashboard.':'Your sign-in could not be confirmed. Sign out and sign in again.');}catch{setAccessNotice('Could not reach Cuelo to check access. Your permissions have not changed.');}finally{setCheckingAccess(false);}}const saved=useQuery(api.sources.get,isAuthenticated?{}:'skip');
 const actionRevision=useRef(0);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[eligible,setEligible]=useState(false),[meeting,setMeeting]=useState(false),[checking,setChecking]=useState(true),[call,setCall]=useState<CallView>(initialCallView),[mode,setMode]=useState<'generic'|'document'|null>(null),[chosen,setChosen]=useState(''),[editing,setEditing]=useState(false),[source,setSource]=useState<Source|null>(null);
 useEffect(()=>{let alive=true,pending=false;async function poll(){if(pending)return;pending=true;try{const status=await command('sidebar-status');if(alive){setEligible(status.eligible===true);setMeeting(status.meeting===true);setCall((status.view??initialCallView) as CallView);setChecking(false);}}catch(e){if(alive){setError(e instanceof Error?e.message:'Cuelo could not connect.');setChecking(false);}}finally{pending=false;}}void poll();const timer=setInterval(()=>{void poll();},750);return()=>{alive=false;clearInterval(timer);};},[]);
 useEffect(()=>{if(!editing)setSource(saved??null);},[saved,editing]);
 useEffect(()=>{if(source?.id!==chosen)setChosen('');},[source?.id]);
 async function act(type:string){const attempt=++actionRevision.current;setBusy(true);setError('');try{if(type==='signin')await signIn('google');else if(type==='signout'){await command('stop');await signOut();}else if(type==='start'){
  await command('start',{resume:call.state==='paused',mode,...(mode==='document'&&source?{sourceId:source.id,sourceTitle:source.title}:{})});
 }else await command(type);}catch(e){setError(e instanceof Error?e.message:'This action could not finish. Try again.');}finally{if(attempt===actionRevision.current)setBusy(false);}}
 const screen=sidebarScreen({checking,meeting,authLoading:isLoading,authenticated:isAuthenticated,accessLoading:access===undefined});const blocked=startBlock({eligible,invited:!!access?.invited,enabled:!!access?.liveEnabled,busy:busy||call.controlsBusy,mode,sourceSelected:!!source&&chosen===source.id,sourceLoading:saved===undefined&&!editing});
 const testVersion=backend.includes('calculating-gecko-263');const active=call.state!=='idle';
 return <><header><strong>Cuelo</strong><span>{testVersion?`Test version${active?` · ${call.state}`:''}`:active?call.state:'Beside your call'}</span></header><main>
 {active?<><p role="status">{call.message}</p>{call.warning&&<p id="warning">Five minutes remain. Cuelo stops at 60 minutes; Meet can continue.</p>}<p className="supporting">{call.mode==='generic'?'Generic answers · Not from your document':`Answers from ${call.sourceTitle??'your selected source'}`}</p>
 {call.audioStats&&<details><summary>Check audio continuity</summary>{call.audioStats.meetingTracks!==undefined&&<p>{call.audioStats.meetingTracks} meeting audio tracks · Your microphone: {call.audioStats.microphoneState==='unmuted'?'on':call.audioStats.microphoneState==='muted'?'muted in Meet':'off — Meet mute state could not be confirmed'}</p>}<p>Meeting frames: {call.audioStats.customerFrames} · Microphone frames: {call.audioStats.microphoneFrames}</p><p>Largest gap: meeting {call.audioStats.customerMaxGapMs} ms · microphone {call.audioStats.microphoneMaxGapMs} ms</p><p className="supporting">Only audio delivery counts are shown. No call text or audio is saved here.</p></details>}
 {testVersion&&call.answerDiagnostics&&<details><summary>Check answer attempts</summary><p>Speech starts: {call.answerDiagnostics.speechStarts} · Requests sent: {call.answerDiagnostics.requests} · Responses received: {call.answerDiagnostics.responses} · Answers displayed: {call.answerDiagnostics.displayed}</p><ol>{call.answerDiagnostics.events.map((event,index)=><li key={index}>{event}</li>)}</ol><p className="supporting">Latest events first. No audio or conversation text is stored in this check. Conversation, recognised questions and interrupted requests are reported separately.</p></details>}
 {call.questionQueue&&<section aria-label="Waiting questions">{call.questionQueue.checking>0&&<p role="status">Checking {call.questionQueue.checking} customer speech segment{call.questionQueue.checking===1?'':'s'} for questions.</p>}{call.questionQueue.questions.length>0&&<><h2>Questions to answer</h2><ol>{call.questionQueue.questions.map((question,index)=><li key={index}>{question}{index===0&&call.questionQueue?.answering?' — finding the answer':''}</li>)}</ol></>}</section>}
 {call.answerNotice&&<p role="status">{call.answerNotice.message}<br/>Question: {call.answerNotice.question}</p>}
 <section aria-label="Current answer" aria-busy={call.busy}>
 {call.busy&&<p role="status">Finding the answer…</p>}
 {call.result?<><p className="answer-question">{call.result.question}</p><AnswerCard result={call.result} sourceLinks={false}/></>:<section className="answer-panel" aria-label="Answer"><h2>Cuelo’s answer</h2><p>{call.busy?'Finding your first answer…':'The customer’s next question will appear here with its answer.'}</p></section>}
 </section>
 {(call.previousAnswers??[]).length>0&&<section aria-label="Previous answers"><h2>Previous answers</h2>{call.previousAnswers.map((answer,index)=><div className="previous-answer" key={call.previousAnswers.length-index}><p className="answer-question">{answer.question}</p><AnswerCard result={answer} sourceLinks={false}/></div>)}</section>}
 <button disabled={busy||call.controlsBusy||(call.state==='connecting'||call.state==='limited')} onClick={()=>{void act(call.state==='paused'?'start':'pause');}}>{call.state==='paused'?'Resume':'Pause'}</button><button className="secondary" disabled={call.controlsBusy} onClick={()=>{void act('stop');}}>Stop</button></>:
 screen==='checking-meeting'?<p role="status">Checking your meeting…</p>:screen==='no-meeting'?<><h1>You’re signed in to Cuelo.</h1><p>Join a Meet call. Cuelo will detect it here automatically.</p><p className="supporting">You’re also signed in on the Cuelo website in this Chrome profile. Audio is off until you start Cuelo.</p></>:
 screen==='checking-account'?<p role="status">Checking your remembered sign-in…</p>:screen==='sign-in'?<><h1>Sign in to Cuelo.</h1><p>Sign in with Google to choose your source and start.</p><button disabled={busy} onClick={()=>{void act('signin');}}>{busy?'Finish Google sign-in…':'Continue with Google'}</button></>:
 screen==='checking-access'?<p role="status">Checking call access…</p>:
 <><h1>How should Cuelo answer?</h1><fieldset><legend>Answer mode</legend><label><input type="radio" name="mode" checked={mode==='generic'} onChange={()=>setMode('generic')}/> Generic answers</label><label><input type="radio" name="mode" checked={mode==='document'} onChange={()=>setMode('document')}/> Answers from my document</label></fieldset>
 {mode==='generic'&&<p className="supporting">Every answer says “Not from your document”.</p>}
 {mode==='document'&&<><label htmlFor="source">Choose your source</label><select id="source" disabled={saved===undefined&&!editing} value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">{saved===undefined&&!editing?'Loading your saved source…':source?'Select a source':'No saved source found'}</option>{source&&<option value={source.id}>{source.title}{source.saved?'':' (temporary)'}</option>}</select>{source&&chosen===source.id&&<p role="status">Source ready: {source.title}</p>}{saved===null&&!source&&<p className="supporting">No source is saved to this Google account. Use the same account you used on the Cuelo website, or add a source here.</p>}<button className="secondary" onClick={()=>setEditing(!editing)}>{editing?'Return to source selection':'Add a new source'}</button>{editing&&<SourceManager accountOnly savedOnly sidebarAdd onSourceChanged={next=>{setSource(next);if(next&&next.id!==source?.id){setChosen(next.id);setEditing(false);}}}/>}</>}
 <button disabled={blocked!==null} onClick={()=>{void act('start');}}>{busy?'Connecting…':'Start'}</button>{blocked&&<p role="status">{blocked}</p>}<p className="supporting">Capture starts only after Start. Cuelo listens to the customer; your microphone adds context. Leaving Meet stops listening.</p></>}
 {isAuthenticated&&!active&&access&&!access.invited&&<details><summary>Troubleshoot tester access</summary><p>Live account: {backend.includes('deafening-frog-846')?'deafening-frog-846':'calculating-gecko-263'}</p>{accountId?<><label htmlFor="account-id">Signed-in account ID</label><input id="account-id" readOnly value={accountId} onFocus={e=>e.target.select()}/><p className="supporting">Use this exact ID when granting tester access in the matching Convex dashboard.</p></>:<p>Account ID could not be confirmed. Sign out and sign in again.</p>}<button className="secondary" disabled={checkingAccess} onClick={()=>{void checkAccess();}}>{checkingAccess?'Checking…':'Check access again'}</button>{accessNotice&&<p role="status">{accessNotice}</p>}</details>}
 {!active&&call.message!==initialCallView.message&&<p role="status">{call.message}</p>}{busy&&!active&&isAuthenticated&&<button className="secondary" onClick={()=>{void act('stop');}}>Cancel connection</button>}{error&&<p role="alert">{error}</p>}{isAuthenticated&&!active&&<button className="secondary" disabled={busy} onClick={()=>{void act('signout');}}>Sign out</button>}
 </main></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><ExtensionAuthProvider client={new ConvexReactClient(backend)} popup={googlePopup}><Sidebar/></ExtensionAuthProvider></React.StrictMode>);
