import {test} from 'node:test';import assert from 'node:assert/strict';
import {liveCallConfig,checkCallText,MAX_CALL_TEXT_CHARACTERS,MAX_CALL_UTTERANCES} from '../convex/liveCallPolicy';
import {createUtteranceAssembler} from '../src/liveTranscript';
test('live admission requires explicit paid flags and every approved testing allowance',()=>{const env={LIVE_CALL_TESTING_ENABLED:'true',V1_PAID_TESTING_ENABLED:'true',DEEPGRAM_API_KEY:'fake',OPENAI_API_KEY:'fake',LIVE_CALL_TEST_SESSION_LIMIT:'1',LIVE_CALL_MAX_CONNECTIONS:'2',LIVE_CALL_MAX_DETECTIONS:'12',LIVE_CALL_MAX_ANSWERS:'4',LIVE_CALL_RESERVE_PAISE:'10000'};assert.ok(liveCallConfig(env));for(const key of Object.keys(env))assert.equal(liveCallConfig({...env,[key]:undefined}),null,key);assert.equal(liveCallConfig({...env,LIVE_CALL_RESERVE_PAISE:'-1'}),null);assert.equal(liveCallConfig({...env,LIVE_CALL_MAX_ANSWERS:'1000'}),null);});
test('60-minute context has explicit generous capacity and never silently truncates oversized turns',()=>{assert.equal(checkCallText('  Example question  ',100,1),'Example question');assert.throws(()=>checkCallText('a'.repeat(2001),0,0),/too long/);assert.throws(()=>checkCallText('word',MAX_CALL_TEXT_CHARACTERS-1,0),/capacity/);assert.throws(()=>checkCallText('word',0,MAX_CALL_UTTERANCES),/capacity/);assert.ok(MAX_CALL_TEXT_CHARACTERS>2*60*150*6);});
test('final segments accumulate once; interim results do not become questions; microphone never cancels answers',()=>{let began=0;const turns:string[]=[];let failures=0;const receive=createUtteranceAssembler({speaker:'customer',onCustomerSpeech:()=>began++,onTurn:text=>turns.push(text),onFailure:()=>failures++});const frame=(text:string,start:number,final:boolean,end=false)=>({type:'Results',start,is_final:final,speech_final:end,channel:{alternatives:[{transcript:text,confidence:.9}]}});receive(frame('What is',0,false));assert.equal(turns.length,0);receive(frame('What is',0,true));receive(frame('What is',0,true));receive(frame('single sign-on?',1,true,true));assert.deepEqual(turns,['What is single sign-on?']);assert.equal(began,1);receive({type:'UtteranceEnd'});assert.equal(turns.length,1);const mic=createUtteranceAssembler({speaker:'salesperson',onCustomerSpeech:()=>began++,onTurn:text=>turns.push(text),onFailure:()=>failures++});mic(frame('Can you explain our product?',0,true,true));assert.equal(began,1);assert.equal(turns.length,2);assert.equal(failures,0);});
test('uncertain speech is not submitted; oversized transcript stops instead of cutting it',()=>{const turns:string[]=[];let failures=0;const receive=createUtteranceAssembler({speaker:'customer',onCustomerSpeech:()=>{},onTurn:t=>turns.push(t),onFailure:()=>failures++});receive({type:'Results',is_final:true,speech_final:true,channel:{alternatives:[{transcript:'uncertain',confidence:.2}]}});assert.deepEqual(turns,[]);receive({type:'Results',is_final:true,channel:{alternatives:[{transcript:'x'.repeat(2001),confidence:.9}]}});assert.equal(failures,1);assert.deepEqual(turns,[]);});

test('replayed final speech is ignored across flushes while a spoken repeat remains a new turn',()=>{
 const turns:string[]=[];const receive=createUtteranceAssembler({speaker:'customer',onCustomerSpeech:()=>{},onFailure:()=>{},onTurn:t=>turns.push(t)});
 const final=(start:number)=>({type:'Results',start,is_final:true,speech_final:true,channel:{alternatives:[{transcript:'What is the price?',confidence:.95}]}});
 receive(final(1));receive(final(1));receive(final(3));assert.deepEqual(turns,['What is the price?','What is the price?']);
});
