// Integrated content-script routing with simulated worklets. No real browser/provider.
import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
async function harness(failModule=false){let listener:any,closed=0;const messages:any[]=[],processors:any[]=[];let loaded=0;
 class Node{gain={value:1};connect(){}disconnect(){}start(){}}
 const context={audioWorklet:{addModule:async()=>{loaded++;if(failModule)throw Error('Module blocked');}},createGain:()=>new Node(),createConstantSource:()=>new Node()};
 class Probe{state='idle';message='off';inputs=new Map();context=context;sink=new Node();micInput={source:new Node()};deadline=Date.now()+3600000;deadlineMono=performance.now()+3600000;constructor(_env:any){}async start(){this.state='listening';}scan(){}status(){return {state:this.state};}stop(){this.state='idle';closed++;return this.status();}}
 class Worklet extends Node{port:any={};constructor(){super();processors.push(this);queueMicrotask(()=>this.port.onmessage?.({data:new ArrayBuffer(1600)}));}}
 const scope:any={CueloMeetAudioProbe:Probe,AudioWorkletNode:Worklet,chrome:{runtime:{id:'cuelo',getURL:(path:string)=>`chrome-extension://cuelo/${path}`,onMessage:{addListener:(f:any)=>{listener=f;}},sendMessage:async(message:any)=>{messages.push(message);return {};}}},addEventListener(){},setTimeout,clearTimeout,setInterval,clearInterval,Date,performance,ArrayBuffer,Uint8Array,Set,Error,btoa};
 vm.runInNewContext(await readFile('extension/meet/meet-audio.js','utf8'),scope);const nonce='a'.repeat(64);
 const request=(type:string,extra:any={},trusted=true)=>new Promise<any>(resolve=>{if(!listener({to:'meet-audio',type,nonce,...extra},{id:trusted?'cuelo':'other'},resolve))resolve(undefined);});
 return {request,nonce,messages,processors,loaded:()=>loaded,closed:()=>closed,flush:()=>new Promise(r=>setTimeout(r,0))};
}
test('both worklet inputs are checked before forwarding; streaming begins only after admitted deadline',async()=>{const h=await harness();assert.equal((await h.request('prepare')).ready,true);assert.equal(h.loaded(),1);assert.equal(h.processors.length,2);assert.equal(h.messages.length,0,'local preparation forwards no audio');await h.request('stream',{deadline:Date.now()+3600000});for(const processor of h.processors)processor.port.onmessage({data:new ArrayBuffer(1600)});await h.flush();assert.deepEqual(h.messages.map(m=>m.speaker),['customer','salesperson']);assert.ok(h.messages.every(m=>m.frame.length===2136&&m.sequence===1));await h.request('stop');assert.equal(h.closed(),1);assert.ok(h.processors.every(p=>p.port.onmessage===null));});
test('worklet restriction fails and releases local capture before any audio forwarding',async()=>{const h=await harness(true);assert.match((await h.request('prepare')).error,/Module blocked/);assert.equal(h.closed(),1);assert.equal(h.messages.length,0);});
test('expired deadlines, wrong nonce and untrusted callers cannot start forwarding',async()=>{const h=await harness();assert.equal(await h.request('prepare',{},false),undefined);await h.request('prepare');assert.match((await h.request('stream',{nonce:'b'.repeat(64),deadline:Date.now()+1000})).error,/Old/);assert.match((await h.request('stream',{deadline:0})).error,/expired/);assert.equal(h.messages.length,0);await h.request('stop');});
