// Simulated media tracks and Chrome APIs; real Meet/audio remains a manual check.
import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
async function harness(){let joined=true,online=true,mute='unmuted',now=1000,mono=0,permission='granted',elements:any[]=[],pendingMic:any=null,resumeError=false;const tracks:any[]=[],contexts:any[]=[],timers=new Map();let timerId=0;
 const track=(id:string,sample=0)=>{const t:any={id,kind:'audio',readyState:'live',enabled:true,sample,stops:0,stop(){this.stops++;this.readyState='ended';},clone(){return track(id+'-clone',sample);}};tracks.push(t);return t;};
 const stream=(values:any[])=>({getTracks:()=>values,getAudioTracks:()=>values.filter(t=>t.kind==='audio')});
 class Context{state='running';destination={};sources:any[]=[];last:any;createGain(){return {gain:{value:1},connect(){},disconnect(){}};}createMediaStreamSource(s:any){const node={sample:s.getAudioTracks()[0].sample,connect:(target:any)=>{target.sample=node.sample;},disconnect(){}};this.sources.push(node);return node;}createAnalyser(){return {fftSize:2048,sample:0,connect(){},disconnect(){},getFloatTimeDomainData(buffer:Float32Array){buffer.fill(this.sample);}};}async close(){this.state='closed';}}
 const env={meeting:()=>joined?'joined':'left',microphoneState:()=>mute,elements:()=>elements,permission:async()=>permission,microphone:async()=>pendingMic?await new Promise(r=>{pendingMic=r;}):stream([track('mic',.1)]),stream,audioContext:()=>{const c=new Context();contexts.push(c);return c;},resume:async()=>{if(resumeError)throw Error('Processing unavailable');},now:()=>now,monotonic:()=>mono,online:()=>online,setInterval:(fn:any)=>{const id=++timerId;timers.set(id,fn);return id;},clearInterval:(id:any)=>timers.delete(id)};
 const scope:any={Float32Array,Map,Error};vm.runInNewContext(await readFile('extension/meet/meet-audio-core.js','utf8'),scope);const probe=new scope.CueloMeetAudioProbe(env);
 return {probe,track,stream,tracks,contexts,timers,elements:(value:any[])=>{elements=value;},mute:(value:string)=>{mute=value;},leave:()=>{joined=false;},offline:()=>{online=false;},permission:(value:string)=>{permission=value;},advance:(ms:number)=>{now+=ms;mono+=ms;},backwards:()=>{now-=3600000;},holdMic:()=>{pendingMic=true;},releaseMic:()=>{pendingMic(stream([track('late-mic',.1)]));},failResume:()=>{resumeError=true;}};
}
const element=(stream:any,extra:any={})=>({srcObject:stream,muted:false,paused:false,ended:false,volume:1,...extra});
test('separate local meters ignore muted preview, deduplicate remote tracks and never stop Meet originals',async()=>{
 const h=await harness(),remote=h.track('remote',.2),local=h.track('local',.8);h.elements([element(h.stream([remote])),element(h.stream([remote])),element(h.stream([local]),{muted:true})]);
 const result=await h.probe.start();assert.equal(result.meetingTracks,1);assert.ok(result.meetingLevel>.5&&result.meetingLevel<.7);assert.ok(result.microphoneLevel>.2&&result.microphoneLevel<.4);h.probe.stop();assert.equal(remote.stops,0);assert.equal(local.stops,0);assert.equal(h.tracks.find(t=>t.id==='remote-clone').stops,1);assert.equal(h.tracks.find(t=>t.id==='mic').stops,1);assert.equal(h.contexts[0].state,'closed');
});
test('joining/leaving participants replaces candidate tracks and releases only clones',async()=>{const h=await harness(),first=h.track('first',.2),second=h.track('second',.3);h.elements([element(h.stream([first]))]);await h.probe.start();h.elements([element(h.stream([second]))]);assert.equal(h.probe.status().meetingTracks,1);assert.equal(h.tracks.find(t=>t.id==='first-clone').stops,1);assert.equal(first.stops,0);assert.ok(h.probe.status().meetingLevel>.8);h.elements([]);assert.equal(h.probe.status().meetingTracks,0);assert.equal(second.stops,0);h.probe.stop();});
test('Meet mute and unknown mute state disable microphone input while remote audio continues',async()=>{const h=await harness(),remote=h.track('remote',.2);h.elements([element(h.stream([remote]))]);await h.probe.start();h.mute('muted');assert.equal(h.probe.status().microphoneLevel,0);assert.equal(h.tracks.find(t=>t.id==='mic').enabled,false);assert.ok(h.probe.status().meetingLevel>.5);h.mute('unknown');assert.equal(h.probe.status().microphoneLevel,0);h.mute('unmuted');assert.ok(h.probe.status().microphoneLevel>.2);h.probe.stop();});
test('permission absent never requests audio; late microphone after Stop is released',async()=>{const h=await harness();h.permission('prompt');await assert.rejects(h.probe.start(),/Allow your microphone/);assert.equal(h.tracks.length,0);assert.equal(h.contexts.length,0);h.permission('granted');h.holdMic();const pending=h.probe.start();await new Promise(r=>setTimeout(r,0));h.probe.stop();h.releaseMic();await pending;assert.equal(h.tracks[0].stops,1);assert.equal(h.probe.status().state,'idle');});
test('Pause releases input, Resume preserves deadline and original cutoff survives backwards clock',async()=>{const h=await harness();await h.probe.start();h.advance(3300000);assert.equal(h.probe.status().warning,true);h.probe.pause();assert.equal(h.probe.status().microphoneLevel,0);assert.equal(h.tracks[0].stops,1);await h.probe.start();assert.equal(h.timers.size,1);h.backwards();h.advance(300000);assert.equal(h.probe.status().state,'idle');assert.match(h.probe.status().message,/60-minute/);assert.equal(h.timers.size,0);});
test('meeting departure, missing device, offline and audio-context failure clean up',async()=>{for(const reason of ['leave','offline','device']){const h=await harness();await h.probe.start();if(reason==='leave')h.leave();else if(reason==='offline')h.offline();else h.tracks[0].readyState='ended';assert.equal(h.probe.status().state,'idle');assert.equal(h.contexts[0].state,'closed');assert.equal(h.timers.size,0);}const failed=await harness();failed.failResume();await assert.rejects(failed.probe.start(),/Processing unavailable/);assert.equal(failed.tracks[0].stops,1);assert.equal(failed.contexts[0].state,'closed');});

async function workerHarness(){let clicked:any,listener:any;const saved:any={};let tab:any={id:1,windowId:7,url:'https://google.com/'},joined=false,state='idle';const routed:any[]=[],opened:any[]=[];
 const chrome={runtime:{id:'cuelo',getURL:(p:string)=>`chrome-extension://cuelo/${p}`,onMessage:{addListener:(f:any)=>{listener=f;}}},storage:{session:{get:async()=>({...saved}),set:async(v:any)=>{Object.assign(saved,v);},remove:async(key:string)=>{delete saved[key];}}},action:{onClicked:{addListener:(f:any)=>{clicked=f;}}},sidePanel:{open:async(v:any)=>{opened.push(v);}},windows:{WINDOW_ID_CURRENT:-2},tabs:{query:async()=>[tab],sendMessage:async(id:number,m:any)=>{routed.push({id,...m});if(m.type==='start')state='listening';if(m.type==='stop')state='idle';if(m.type==='pause')state='paused';return {state,joined};},onRemoved:{addListener(){}}}};
 vm.runInNewContext(await readFile('experiments/meet-page-audio/worker.js','utf8'),{chrome,Error});
 const request=(type:string,trusted=true)=>new Promise<any>(resolve=>{if(!listener({type},{id:trusted?'cuelo':'foreign',url:chrome.runtime.getURL('sidepanel.html')},resolve))resolve(undefined);});
 return {request,routed,opened,open:()=>clicked(tab),meet:()=>{tab={id:2,windowId:7,url:'https://meet.google.com/abc-defg-hij'};joined=true;},random:()=>{tab={id:3,windowId:7,url:'https://google.com/'};},flush:()=>new Promise(r=>setTimeout(r,0))};
}
test('prototype Start routes to a new joined Meet after sidebar opened on unrelated tab, without a second invocation',async()=>{const h=await workerHarness();h.open();await h.flush();assert.equal((await h.request('status')).joined,false);h.meet();assert.equal((await h.request('status')).joined,true);assert.equal((await h.request('start')).state,'listening');assert.equal(h.routed.find(m=>m.type==='start')?.id,2);h.random();assert.equal((await h.request('status')).state,'listening');await h.request('stop');assert.equal(h.routed.find(m=>m.type==='stop')?.id,2);assert.equal(h.opened.length,1);});
test('prototype rejects untrusted requests and cannot start outside a joined Meet',async()=>{const h=await workerHarness();assert.equal(await h.request('start',false),undefined);assert.equal(h.routed.length,0);assert.ok((await h.request('start')).error);assert.equal(h.routed.some(m=>m.type==='start'),false);});

test('content adapter calls browser timers with the browser receiver, not its own environment object (simulated)',async()=>{
 let adapter:any,started=0,cleared=0;
 const scope:any={CueloMeetAudioProbe:class{constructor(env:any){adapter=env;}},chrome:{runtime:{onMessage:{addListener(){}}}},addEventListener(){},setInterval:function(this:any){if(this&&typeof this.permission==='function')throw new TypeError('Illegal invocation');started++;return 9;},clearInterval:function(this:any,id:number){if(this&&typeof this.permission==='function')throw new TypeError('Illegal invocation');assert.equal(id,9);cleared++;}};
 vm.runInNewContext(await readFile('experiments/meet-page-audio/content.js','utf8'),scope);
 assert.equal(adapter.setInterval(()=>{},250),9);adapter.clearInterval(9);assert.equal(started,1);assert.equal(cleared,1);
});
