// Simulated Chrome APIs only. No Google Meet, microphone or paid provider calls.
import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
function event(){let fn:any;return {addListener:(f:any)=>fn=f,fire:(...args:any[])=>fn?.(...args)};}
async function harness(){const messages=event(),action=event(),removed=event();let tab={id:4,windowId:1,url:'https://google.com/'},inMeeting=false,exists=false,bound:any=null,sidebarWindow:any=null;const routed:any[]=[];let queriedWindow:any=null;let state='idle',hold:any=null;
 const chrome={runtime:{id:'extension',getURL:(p:string)=>`chrome-extension://extension/${p}`,getContexts:async()=>exists?[{}]:[],onMessage:messages,sendMessage:async(m:any)=>{routed.push(m);if(m.type==='status')return {ready:true,view:{state}};if(m.type==='start'){state='listening';return {view:{state}};}if(m.type==='pause')state='paused';if(m.type==='stop')state='idle';return {view:{state}};}},storage:{session:{get:async()=>({cueloCallBinding:bound,cueloSidebarWindowId:sidebarWindow}),set:async(v:any)=>{if('cueloCallBinding' in v)bound=v.cueloCallBinding;if('cueloSidebarWindowId' in v)sidebarWindow=v.cueloSidebarWindowId;}},local:{get:async()=>({}),set:async()=>{},remove:async()=>{}}},action:{onClicked:action},windows:{WINDOW_ID_CURRENT:-2},tabs:{onRemoved:removed,query:async(options:any)=>{queriedWindow=options.windowId;return [tab];},sendMessage:async(id:number,m:any)=>{routed.push({page:id,...m});return {joined:inMeeting,...(m.to==='meet-audio'&&m.type==='status'?{state:'listening',meetingTracks:1,microphoneState:'unmuted'}:{})};}},offscreen:{createDocument:async()=>{if(hold)await new Promise(r=>hold=r);exists=true;},closeDocument:async()=>{exists=false;}},tabCapture:{getMediaStreamId:async()=>{routed.push({captured:bound.tabId});return 'opaque';}}};
 vm.runInNewContext(await readFile('extension/meet/call-worker.js','utf8'),{chrome,setTimeout,crypto:globalThis.crypto,Uint8Array});const flush=()=>new Promise(r=>setTimeout(r,0));const panel={id:'extension',url:chrome.runtime.getURL('auth-check.html')};
 const request=(m:any,s=panel)=>new Promise<any>(resolve=>{if(!messages.fire(m,s,resolve))resolve(undefined);});
 return {request,flush,action,removed,routed,queriedWindow:()=>queriedWindow,meet:()=>{tab={...tab,url:'https://meet.google.com/abc-defg-hij'};inMeeting=true;},leave:()=>inMeeting=false,tab:()=>tab,random:()=>{tab={...tab,id:9,url:'https://google.com/'};},hold:()=>hold=true,release:()=>hold?.(),audio:{id:'extension',url:chrome.runtime.getURL('call.html')}};
}
test('joined Meet allows Start after sidebar opened on another tab; bound page supplies audio without tabCapture',async()=>{const h=await harness();h.action.fire(h.tab());await h.flush();assert.equal((await h.request({type:'sidebar-status'})).eligible,false);h.meet();assert.equal((await h.request({type:'sidebar-status'})).eligible,true);await h.request({type:'start',mode:'generic'});const start=h.routed.find(x=>x.type==='start');assert.match(start.nonce,/^[a-f0-9]{64}$/);assert.equal(start.streamId,undefined);assert.deepEqual(h.routed.filter(x=>x.captured),[]);h.random();h.action.fire(h.tab());await h.flush();assert.equal((await h.request({type:'sidebar-status'})).view.state,'listening');assert.equal(h.routed.some(x=>x.type==='tabs.create'),false);});
test('Pause retains binding, Resume uses same tab, meeting end stops and closes capture',async()=>{const h=await harness();h.meet();h.action.fire(h.tab());await h.flush();await h.request({type:'start',mode:'generic'});await h.request({type:'pause'});assert.equal((await h.request({type:'sidebar-status'})).view.state,'paused');await h.request({type:'start',resume:true});h.leave();await h.request({type:'call-alive'},h.audio);assert.equal((await h.request({type:'sidebar-status'})).eligible,false);assert.equal(h.routed.filter(x=>x.type==='stop'&&x.to==='call').length,1);});
test('Stop cancels a late offscreen creation before any audio or provider start',async()=>{const h=await harness();h.meet();h.action.fire(h.tab());await h.flush();h.hold();const pending=h.request({type:'start',mode:'generic'});await h.flush();await h.request({type:'stop'});h.release();assert.match((await pending).error,/cancelled/);assert.equal(h.routed.some(x=>x.captured||x.type==='start'),false);});
test('untrusted pages cannot start capture or read stored login',async()=>{const h=await harness();const foreign={id:'extension',url:'https://meet.google.com/abc-defg-hij'};assert.equal(await h.request({type:'start',mode:'generic'},foreign),undefined);assert.equal(await h.request({type:'auth-storage',action:'get',key:'__convexAuthJWT_any'},foreign),undefined);assert.match((await h.request({type:'auth-storage',action:'get',key:'private-key'},h.audio)).error,/Invalid/);assert.equal(h.routed.length,0);});

test('sidebar opened before Meet detects the call without confusing detection with capture permission',async()=>{const h=await harness();h.action.fire(h.tab());await h.flush();h.meet();const status=await h.request({type:'sidebar-status'});assert.equal(status.meeting,true);assert.equal(status.eligible,true);assert.equal(status.setupAvailable,true);assert.equal(h.queriedWindow(),1);});
test('sign-in popup focus must not change the sidebar meeting window',async()=>{const h=await harness();h.meet();h.action.fire(h.tab());await h.flush();await h.request({type:'sidebar-status'});assert.equal(h.queriedWindow(),1);});

test('another Meet or nonce cannot forward frames into the bound session',async()=>{const h=await harness();h.meet();h.action.fire(h.tab());await h.flush();await h.request({type:'start',mode:'generic'});const nonce=h.routed.find(m=>m.type==='start').nonce;const sender={id:'extension',frameId:0,tab:h.tab()};const message={type:'meet-audio-frame',nonce,speaker:'customer',sequence:1,frame:'A'.repeat(2136)};await h.request(message,sender);assert.equal(h.routed.filter(m=>m.type==='audio-frame').length,1);assert.match((await h.request({...message,nonce:'0'.repeat(64)},sender)).error,/sender/);assert.match((await h.request(message,{...sender,tab:{...h.tab(),id:88}})).error,/sender/);assert.match((await h.request(message,{...sender,frameId:1})).error,/sender/);assert.equal(h.routed.filter(m=>m.type==='audio-frame').length,1);});
test('duplicate Start cannot replace an active audio binding',async()=>{const h=await harness();h.meet();h.action.fire(h.tab());await h.flush();await h.request({type:'start',mode:'generic'});const nonce=h.routed.find(m=>m.type==='start').nonce;assert.match((await h.request({type:'start',mode:'generic'})).error,/Stop/);const sender={id:'extension',frameId:0,tab:h.tab()};await h.request({type:'meet-audio-frame',nonce,speaker:'customer',sequence:1,frame:'A'.repeat(2136)},sender);assert.equal(h.routed.filter(m=>m.type==='audio-frame').length,1);});
test('health reports real page input metadata while another tab is active',async()=>{const h=await harness();h.meet();h.action.fire(h.tab());await h.flush();await h.request({type:'start',mode:'generic'});h.random();const health=await h.request({type:'call-alive'},h.audio);assert.equal(health.audio.meetingTracks,1);assert.equal(health.audio.microphoneState,'unmuted');assert.equal(h.routed.some(m=>m.type==='stop'),false);});
