// Owns the joined Meet binding and trusted audio routing; call.html owns audio and the existing backend path.
let creating=null, stopping=null, lastView=null, revision=0, starting=false;
const binding=()=>chrome.storage.session.get('cueloCallBinding').then(v=>v.cueloCallBinding??null);
const sidebarWindow=()=>chrome.storage.session.get('cueloSidebarWindowId').then(v=>v.cueloSidebarWindowId);
const save=value=>chrome.storage.session.set({cueloCallBinding:value});
const isMeet=tab=>typeof tab?.url==='string'&&/^https:\/\/meet\.google\.com\/[a-z]{3}-[a-z]{4}-[a-z]{3}(?:[/?#]|$)/.test(tab.url);
const joined=async id=>{try{return (await chrome.tabs.sendMessage(id,{type:'call-state'})).joined===true;}catch{return false;}};
const hasEngine=async()=> (await chrome.runtime.getContexts({contextTypes:['OFFSCREEN_DOCUMENT'],documentUrls:[chrome.runtime.getURL('call.html')]})).length>0;
const engine=message=>chrome.runtime.sendMessage({...message,to:'call'});
async function ensureEngine(){if(await hasEngine())return;if(!creating)creating=chrome.offscreen.createDocument({url:'call.html',reasons:['USER_MEDIA'],justification:'Keep the authenticated speech connection alive for separate Meet-page audio inputs.'}).finally(()=>{creating=null;});await creating;}
async function view(){if(!await hasEngine())return lastView?{...lastView,state:'idle',busy:false,controlsBusy:false,result:null,previousAnswers:[]}:null;try{return (await engine({type:'status'})).view??null;}catch{return null;}}
async function stop(message){revision++;starting=false;if(stopping)return stopping;stopping=(async()=>{const bound=await binding();if(bound?.nonce)await chrome.tabs.sendMessage(bound.tabId,{to:'meet-audio',type:'stop',nonce:bound.nonce}).catch(()=>{});if(await hasEngine()){await engine({type:'stop',message});await chrome.offscreen.closeDocument();}})().finally(()=>{stopping=null;});return stopping;}
chrome.action.onClicked.addListener(tab=>{void(async()=>{await chrome.storage.session.set({cueloSidebarWindowId:tab.windowId});const current=await view();if(starting||current&&current.state!=='idle')return;revision++;await save(isMeet(tab)?{tabId:tab.id,windowId:tab.windowId}:null);})().catch(()=>{});});
async function status(sender){const current=await view(),bound=await binding();if(current&&current.state!=='idle')return {eligible:true,view:current};const tabs=await chrome.tabs.query({active:true,windowId:sender.tab?.windowId??await sidebarWindow()??chrome.windows.WINDOW_ID_CURRENT});const tab=tabs[0];const inMeeting=isMeet(tab)&&await joined(tab.id);return {eligible:inMeeting,setupAvailable:inMeeting,meeting:inMeeting,view:current};}
async function start(message){
 if(stopping)throw Error('Cuelo is still stopping.');if(starting)throw Error('Cuelo is already connecting.');starting=true;const run=++revision;
 try{const existing=await view();if(!message.resume&&existing&&existing.state!=='idle')throw Error('Stop the current Cuelo session first.');let bound=await binding();if(!message.resume){const tabs=await chrome.tabs.query({active:true,windowId:await sidebarWindow()??chrome.windows.WINDOW_ID_CURRENT}),tab=tabs[0];if(!isMeet(tab)||!await joined(tab.id))throw Error('Join a Meet call before starting Cuelo.');bound={tabId:tab.id,windowId:tab.windowId};}if(!bound||!await joined(bound.tabId))throw Error('Join a Meet call before starting Cuelo.');
  const bytes=crypto.getRandomValues(new Uint8Array(32)),nonce=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');bound={...bound,nonce};await save(bound);if(run!==revision)throw Error('Start cancelled.');
  if(!message.resume&&await hasEngine()){const current=await view();if(current&&current.state!=='idle')throw Error('Stop the current Cuelo session first.');await chrome.offscreen.closeDocument();}await ensureEngine();
  for(let i=0;i<100;i++){if(run!==revision)throw Error('Start cancelled.');const state=await engine({type:'status'}).catch(()=>null);if(state?.ready)break;if(i===99)throw Error('Cuelo’s listening page could not get ready. Reload the extension and try again.');await new Promise(resolve=>setTimeout(resolve,100));}
  if(run!==revision||!await joined(bound.tabId))throw Error('The meeting ended before Cuelo connected.');
  const result=await engine({...message,type:'start',nonce});if(result?.error)throw Error(result.error);return result;
 }finally{if(run===revision)starting=false;else if(!starting&&await hasEngine()){const current=await view();if(!current||current.state==='idle')await chrome.offscreen.closeDocument();}}
}
chrome.runtime.onMessage.addListener((message,sender,reply)=>{
 if(message?.to==='call')return;
 const panel=sender.id===chrome.runtime.id&&sender.url===chrome.runtime.getURL('auth-check.html');
 const audio=sender.id===chrome.runtime.id&&sender.url===chrome.runtime.getURL('call.html');
 let task;
 if(audio&&message.type==='auth-storage')task=(async()=>{if(typeof message.key!=='string'||!/^__convexAuth(?:JWT|RefreshToken|OAuthVerifier|ServerStateFetchTime)_cuelosidebarhttps(?:calculatinggecko263|deafeningfrog846)convexcloud$/.test(message.key)||message.key.length>300)throw Error('Invalid sign-in storage request.');if(message.action==='get'){const v=await chrome.storage.local.get(message.key);return {value:typeof v[message.key]==='string'?v[message.key]:null};}if(message.action==='remove'){await chrome.storage.local.remove(message.key);return {};}if(message.action==='set'&&typeof message.value==='string'&&message.value.length<=20000){await chrome.storage.local.set({[message.key]:message.value});return {};}throw Error('Invalid sign-in storage request.');})();
 else if(audio&&message.type==='call-view'){lastView=message.view;task=Promise.resolve({});}
 else if(audio&&message.type==='call-alive')task=(async()=>{const bound=await binding();if(!bound||!await joined(bound.tabId)){await stop('Meeting ended. Audio and transcription are off.');return {};}const current=await view();if(current?.state==='listening'){const health=await chrome.tabs.sendMessage(bound.tabId,{to:'meet-audio',type:'status',nonce:bound.nonce}).catch(()=>null);if(!health||health.error||health.state!=='listening'){await stop('Meeting audio disconnected. Cuelo stopped.');return {};}return {audio:{meetingTracks:health.meetingTracks,microphoneState:health.microphoneState}};}return {};})();
 else if(audio&&message.type==='meet-audio-control')task=(async()=>{const bound=await binding();if(!bound||message.nonce!==bound.nonce)throw Error('Old audio connection.');if(!['prepare','stream','stop','status'].includes(message.operation))throw Error('Unknown audio action.');if(message.operation!=='stop'&&!await joined(bound.tabId))throw Error('The meeting ended.');return chrome.tabs.sendMessage(bound.tabId,{to:'meet-audio',type:message.operation,nonce:bound.nonce,...(message.operation==='stream'?{deadline:message.deadline}:{})});})();
 else if(message.type==='meet-audio-frame'||message.type==='meet-audio-ended')task=(async()=>{const bound=await binding();if(sender.id!==chrome.runtime.id||sender.frameId!==0||!isMeet(sender.tab)||sender.tab?.id!==bound?.tabId||message.nonce!==bound?.nonce)throw Error('Audio sender is not this meeting.');if(message.type==='meet-audio-ended'){await stop(typeof message.message==='string'?message.message.slice(0,200):'Meeting audio disconnected. Cuelo stopped.');return {};}
 if(!['customer','salesperson'].includes(message.speaker)||typeof message.frame!=='string'||message.frame.length!==2136||!Number.isSafeInteger(message.sequence)||message.sequence<1)throw Error('Unreadable meeting audio.');return engine({type:'audio-frame',nonce:bound.nonce,speaker:message.speaker,sequence:message.sequence,frame:message.frame});})();
 else if(panel&&message.type==='sidebar-status')task=status(sender);
 else if(panel&&message.type==='start')task=start(message);
 else if(panel&&message.type==='pause')task=(async()=>{const bound=await binding();if(bound?.nonce)await chrome.tabs.sendMessage(bound.tabId,{to:'meet-audio',type:'stop',nonce:bound.nonce}).catch(()=>{});return engine({type:'pause'});})();
 else if(panel&&message.type==='stop')task=stop('Stopped. Audio and transcription are off.').then(()=>({}));
 else if(message.type==='left'&&sender.id===chrome.runtime.id&&isMeet(sender.tab)&&sender.tab?.id)task=(async()=>{const bound=await binding();if(bound?.tabId===sender.tab.id)await stop('Meeting ended. Audio and transcription are off.');return {};})();
 if(!task)return;void task.then(reply).catch(error=>reply({error:error instanceof Error?error.message:'Cuelo could not finish this action.'}));return true;
});
chrome.tabs.onRemoved.addListener(id=>{void(async()=>{const bound=await binding();if(bound?.tabId===id){await stop('Meet tab closed. Audio and transcription are off.');await save(null);}})().catch(()=>{});});
