// Read the tested Meet-page audio inputs. Only bounded PCM frames and scalar
// health counters go to trusted extension contexts; no credentials enter Meet.
function microphoneState(){for(const control of document.querySelectorAll('button,[role="button"]')){if(!control.getClientRects().length)continue;const label=control.getAttribute('aria-label')??control.getAttribute('data-tooltip')??control.getAttribute('title')??'';if(/^turn on microphone\b/i.test(label))return 'muted';if(/^turn off microphone\b/i.test(label))return 'unmuted';}return 'unknown';}
let nonce=null,streaming=false,inflight={count:0},nodes=[],processors=[],bus=null,sequences={customer:0,salesperson:0},intentional=false;
function releasePcm(){streaming=false;for(const node of processors)node.port.onmessage=null;for(const node of nodes){try{node.disconnect();}catch{}}nodes=[];processors=[];bus=null;}
function endIfIdle(){if(nonce&&probe.state==='idle'&&!intentional){const ended=nonce;nonce=null;releasePcm();void chrome.runtime.sendMessage({type:'meet-audio-ended',nonce:ended,message:probe.message}).catch(()=>{});}}
const probe=new globalThis.CueloMeetAudioProbe({meeting:()=>globalThis.cueloProbeMeetingState(document,location.pathname),microphoneState,elements:()=>document.querySelectorAll('audio,video'),permission:async()=>(await navigator.permissions.query({name:'microphone'})).state,microphone:()=>navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true},video:false}),stream:tracks=>new MediaStream(tracks),audioContext:()=>new AudioContext(),resume:ctx=>new Promise((resolve,reject)=>{const timer=globalThis.setTimeout(()=>reject(Error('Chrome could not activate audio processing.')),5000);ctx.resume().then(()=>{globalThis.clearTimeout(timer);resolve();},()=>{globalThis.clearTimeout(timer);reject(Error('Chrome could not activate audio processing.'));});}),now:()=>Date.now(),monotonic:()=>performance.now(),online:()=>navigator.onLine,setInterval:(fn,delay)=>globalThis.setInterval(()=>{fn();endIfIdle();},delay),clearInterval:id=>globalThis.clearInterval(id)});
const originalScan=probe.scan.bind(probe);probe.scan=()=>{originalScan();if(bus)for(const input of probe.inputs.values())if(!input.forwarded){input.source.connect(bus);input.forwarded=true;}};
function stop(message='Stopped. Audio and transcription are off.'){intentional=true;nonce=null;releasePcm();const result=probe.stop(message);intentional=false;return result;}
function failure(message){probe.stop(message);endIfIdle();}
function encode(frame){const bytes=new Uint8Array(frame);let value='';for(const byte of bytes)value+=String.fromCharCode(byte);return btoa(value);}
function forward(speaker,frame,run){if(!streaming||run!==nonce)return;if(frame.byteLength!==1600||inflight.count>=4){failure('The audio connection could not keep up. Cuelo stopped.');return;}const batch=inflight;batch.count++;const sequence=++sequences[speaker];void chrome.runtime.sendMessage({type:'meet-audio-frame',nonce:run,speaker,sequence,frame:encode(frame)}).then(result=>{if(run===nonce&&result?.error)failure('Meeting audio could not reach Cuelo. Listening stopped.');}).catch(()=>{if(run===nonce)failure('Meeting audio disconnected. Cuelo stopped.');}).finally(()=>{batch.count--;});}
async function prepare(message){if(nonce)throw Error('Stop the previous audio connection first.');if(typeof message.nonce!=='string'||!/^[a-f0-9]{64}$/.test(message.nonce))throw Error('Invalid audio connection.');nonce=message.nonce;inflight={count:0};const run=nonce;try{await probe.start();if(run!==nonce)throw Error('Start cancelled.');await probe.context.audioWorklet.addModule(chrome.runtime.getURL('meet-pcm.js'));if(run!==nonce)throw Error('Start cancelled.');await prepareGraph(run);if(run!==nonce)throw Error('Start cancelled.');return {ready:true,...probe.status()};}catch(error){if(run===nonce)stop();throw error;}}
async function prepareGraph(run){const ctx=probe.context;bus=ctx.createGain();nodes.push(bus);const silence=ctx.createConstantSource(),zero=ctx.createGain();zero.gain.value=0;silence.connect(zero);zero.connect(bus);silence.start();nodes.push(silence,zero);
 await new Promise((resolve,reject)=>{const seen=new Set(),timer=globalThis.setTimeout(()=>reject(Error('Meet audio processing did not produce both inputs. No paid connection started.')),3000);
  try{for(const speaker of ['customer','salesperson']){const processor=new AudioWorkletNode(ctx,'cuelo-live-pcm',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[1],channelCount:1,channelCountMode:'explicit'});nodes.push(processor);processors.push(processor);processor.port.onmessage=event=>{if(run!==nonce)return;if(event.data?.byteLength!==1600){globalThis.clearTimeout(timer);reject(Error('Audio processing returned an unreadable input.'));failure('Unreadable audio. Cuelo stopped.');return;}seen.add(speaker);if(seen.size===2){globalThis.clearTimeout(timer);resolve();}forward(speaker,event.data,run);};(speaker==='customer'?bus:probe.micInput.source).connect(processor);processor.connect(probe.sink);}probe.scan();}catch(error){globalThis.clearTimeout(timer);reject(error);}
 });
}
async function stream(message){if(!nonce||message.nonce!==nonce||probe.state!=='listening'||processors.length!==2)throw Error('Meeting audio is not ready.');if(!Number.isFinite(message.deadline)||message.deadline<=Date.now())throw Error('This call expired.');probe.deadline=Math.min(probe.deadline,message.deadline);probe.deadlineMono=Math.min(probe.deadlineMono,performance.now()+message.deadline-Date.now());sequences={customer:0,salesperson:0};streaming=true;return {ready:true,...probe.status()};}
chrome.runtime.onMessage.addListener((message,sender,reply)=>{
 if(message?.to!=='meet-audio'||sender.id!==chrome.runtime.id)return;
 let action;if(message.type==='prepare')action=prepare(message);else if(message.nonce!==nonce){reply({error:'Old audio connection.'});return;}else if(message.type==='stream')action=stream(message);else if(message.type==='stop')action=Promise.resolve(stop());else if(message.type==='status'){const result=probe.status();endIfIdle();action=Promise.resolve({...result,streaming});}else return;
 void action.then(reply).catch(error=>reply({error:error?.name==='NotAllowedError'?'Meet microphone access was not granted. Allow it in Meet and try Start again.':error?.name==='NotFoundError'?'No microphone found.':error?.name==='NotReadableError'?'Your microphone is unavailable.':error instanceof Error?error.message:'Audio access failed.'}));return true;
});
addEventListener('pagehide',()=>{failure('Meet page closed. Audio and transcription are off.');});addEventListener('offline',()=>{failure('Connection lost. Audio and transcription are off.');});
