import {useEffect,useRef,useState} from 'react';
import {CallPreview} from './CallPreview';
import {Topbar,MicIcon,CallIcon} from './Topbar';
export function Home(){
 const [draggable,setDraggable]=useState(false),[moved,setMoved]=useState(false),[offset,setOffset]=useState({x:0,y:0}),[hint,setHint]=useState(false);
 const start=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);const invitation=useRef<HTMLElement|null>(null);
 useEffect(()=>{const path=()=>{if(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)setOffset({x:Math.sin(window.scrollY/220)*8,y:-Math.min(12,window.scrollY/80)});};window.addEventListener('scroll',path,{passive:true});const timer=setTimeout(()=>{window.removeEventListener('scroll',path);setDraggable(true);},20000);const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))setHint(true);},{threshold:.3});if(invitation.current)observer.observe(invitation.current);return()=>{clearTimeout(timer);window.removeEventListener('scroll',path);observer.disconnect();};},[]);
 const clamp=(x:number,y:number)=>setOffset({x:Math.max(-16,Math.min(16,x)),y:Math.max(-20,Math.min(20,y))});
 return <><Topbar home/><main className="home-page">
 <section className="opening" aria-labelledby="opening-heading"><h1 id="opening-heading">Your quiet assistant<br className="desktop-break"/> for live calls.</h1><p className="home-intro">Ask out loud. Get a quick answer in text. Choose general knowledge or add your document for product-specific answers. Built for salespeople who want to stay in the conversation.</p>
 <div className={`conversation-stage ${moved?'placed':''}`} style={{transform:`translate(${offset.x}px,${offset.y}px)`}}>
 <div className="blob-area"><button type="button" className="blob-handle" disabled={!draggable} aria-label={draggable?'Move Cuelo and its answer card':'Cuelo is idle'} onPointerDown={event=>{if(!draggable)return;event.currentTarget.setPointerCapture(event.pointerId);start.current={x:event.clientX,y:event.clientY,ox:offset.x,oy:offset.y};setMoved(true);}} onPointerMove={event=>{const origin=start.current;if(origin)clamp(origin.ox+event.clientX-origin.x,origin.oy+event.clientY-origin.y);}} onPointerUp={()=>{start.current=null;}} onPointerCancel={()=>{start.current=null;}} onKeyDown={event=>{const directions:Record<string,[number,number]>={ArrowLeft:[-4,0],ArrowRight:[4,0],ArrowUp:[0,-4],ArrowDown:[0,4]};const delta=directions[event.key];if(delta){event.preventDefault();setMoved(true);clamp(offset.x+delta[0],offset.y+delta[1]);}}}><span className="cuelo-blob" aria-hidden="true"><span className="blob-glint"/><span className="blob-face"><span className="blob-eye left-eye"/><span className="blob-eye right-eye"/></span></span></button>
 <p className="blob-caption">Quiet by nature.</p></div>
 <section className="welcome-card" aria-labelledby="welcome-heading"><div className="card-presence"><span aria-hidden="true"/>Cuelo</div><h2 id="welcome-heading">Ask me anything.</h2><p>Tap the mic and speak.<br/>{" "}I’ll reply in text.</p><div className="knowledge-mode">General knowledge</div><p className="provenance">Not from your document</p></section>
 </div>
 <div className="opening-controls"><button className="voice-action" type="button" disabled aria-describedby="voice-unavailable"><MicIcon/>Speak to Cuelo</button><p id="voice-unavailable" className="supporting">Voice answers aren’t available yet. No microphone is listening.</p><a className="quiet-source" href="/?view=sources">For product-specific answers, add a document or help-page link.</a>
 {draggable&&<div className="position-controls"><p>{moved?'Position saved for this page.':'Drag me somewhere comfortable.'}</p><button className="text-button" onClick={()=>{setOffset({x:0,y:0});setMoved(false);}}>Reset position</button></div>}
 </div></section>
 <section ref={invitation} className="call-invitation-section" aria-label="Try Cuelo on a call"><CallPreview/>{hint&&<p className="blob-bubble">Try me on a customer call. Use a sample, or add your own document.</p>}<a className="call-invitation" href="/?view=practice"><CallIcon/><span>Experience Cuelo on a call</span><span className="invitation-arrow" aria-hidden="true"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M5 12h14m-6-6 6 6-6 6"/></svg></span></a></section>
 <footer className="home-footer"><p>Cuelo replies in text. Built for desktop Chrome.</p><div><a href="/?view=answers">Check an answer</a><a href="/?view=evaluation">Slack source check</a></div></footer>
 </main></>;
}
